require:
  - rubocop-rails

inherit_mode:
  merge:
    - Exclude

AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'db/**/*'
    - 'script/**/*'
    - 'node_modules/**/*'
    - 'config/spring.rb'
    - 'config/puma.rb'
    - 'config/initializers/*'
    - 'config/environments/*'
    - 'config/application.rb'
    - 'spec/features/*'

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/MultilineIfModifier:
  Enabled: false

Layout/ArgumentAlignment:
  Enabled: false

Metrics/BlockLength:
 ExcludedMethods: ['describe', 'context', 'feature', 'scenario', 'let']

Layout/LineLength:
  Max: 80

Style/AsciiComments:
  Enabled: false
